### ISSUE TITLE
missing data for 2016 giants games, after October 2nd

### ISSUE THREAD

**Issue by dholbert** [lforrest/isthereagiantsgametoday#25]
http://isthereagiantsgametoday.com/ says "NO" for today, October 10, but http://sanfrancisco.giants.mlb.com/schedule/index.jsp?c_id=sf#y=2016&m=10 shows there being a giants game today (vs the Cubs), as well as one tomorrow and on Thursday (away).

**Comment by dholbert** [comment]
It looks like giants2016schedule.json thinks the last 2016 game was on October 2nd:
https://github.com/lforrest/isthereagiantsgametoday/blob/80d409166a844d34196bcafd9e585fb19e9748af/data/giants2016schedule.json#L960

CCing @brianpgerson  who added that file -- maybe he'd be up for updating it? :)

**Comment by lforrest** [comment]
Thanks for reporting! Let's work to get this updates ASAP.

**Comment by lforrest** [comment]
Here's the rest of the games that have been scheduled. @dholbert or @dailycavalier do you mind putting this into a pull request? Doing so may help the Giants win... ;)

 },
    {
      "date": "10/10/2016",
      "location": "AT&T Park",
      "opponent": "Cubs",
      "time": "6:30pm"
 },
    {
      "date": "10/11/2016",
      "location": "AT&T Park",
      "opponent": "Cubs",
      "time": "5:30pm"
 },
    {
      "date": "10/13/2016",
      "location": "Away",
      "opponent": "Dodgers",
      "time": "1:05pm"
    }
  ]
}

**Comment by brianpgerson** [comment]
@lforrest @dholbert @dailycavalier I can def do this...going to the game today so I'm definitely hoping for the good luck factor here ha.

**Comment by dholbert** [comment]
Thanks to you both!

**Comment by dailycavalier** [comment]
Now fixed. Thank you @dholbert, @brianpgerson and @lforrest!! ⚾️
