### ISSUE TITLE
Stadium name change broke away vs home game recognition

### ISSUE THREAD

**Issue by garrettgalow** [lforrest/isthereagiantsgametoday#36]
https://github.com/lforrest/isthereagiantsgametoday/blob/master/js/site.js#L61

1 line change to update the name of `at&t park` to `oracle stadium`

**Comment by thebrettd** [comment]
😂 GMTA

**Comment by garrettgalow** [comment]
haha

**Comment by thebrettd** [comment]
This can be closed, we merged a fix in #38
