### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by thebrettd** [lforrest/isthereagiantsgametoday#39]
I tried to access http://www.isthereagiantsgametoday.com/ with Google Chrome and got a 403 Forbidden response from the server:

```
Forbidden
You don't have permission to access this resource.Server unable to read htaccess file, denying access to be safe

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by garrettgalow** [comment]
+1

**Comment by garrettgalow** [comment]
reproduces on osx - safari in addition to osx- chrome

Looks to be a server side issue

**Comment by dailycavalier** [comment]
This issue is now fixed. Permissions were accidentally changed for the directory and the change has been reverted. Thanks @thebrettd @garrettgalow!

**Comment by thebrettd** [comment]
Thanks @dailycavalier

**Comment by thebrettd** [comment]
Also confirmed that the BoSox version of this page is broken, and the bay is best.http://istherearedsoxgametoday.com/
