### ISSUE TITLE
Site is broken for 2020

### ISSUE THREAD

**Issue by mattmattmatt** [lforrest/isthereagiantsgametoday#40]
Since `http://www.isthereagiantsgametoday.com/data/giants2020schedule.json` doesn't exist, the site is broken.

**Comment by dailycavalier** [comment]
@mattmattmatt thanks for reporting this.

@thebrettd would you be interested in adding the 2020 schedule data?

**Comment by thebrettd** [comment]
@dailycavalier I submitted a PR to update the schedule: https://github.com/lforrest/isthereagiantsgametoday/pull/41

**Comment by dailycavalier** [comment]
This is now fixed on the site. Thanks to @thebrettd!

**Comment by thebrettd** [comment]
🍾
