### ISSUE TITLE
Updated schedule not displaying

### ISSUE THREAD

**Issue by thebrettd** [lforrest/isthereagiantsgametoday#51]
The website is getting a 404 trying to retrieve the schedule JSON file

http://isthereagiantsgametoday.com/data/giants2023schedule.json

Maybe the webserver needs a bounce? I don't think I typoed anything here :(

https://github.com/lforrest/isthereagiantsgametoday/pull/50

**Comment by dailycavalier** [comment]
@thebrettd @lforrest this is now resolved. I pushed the updated JSON file to production. Thanks for your help and Go Giants! ⚾

**Comment by thebrettd** [comment]
Thanks, I work from home now so I don't have to deal with this traffic anymore, but updating the schedule still gives me a little joy every year 😂

**Comment by dailycavalier** [comment]
Thank you for continuing to update the schedule! It gives Laura and me joy too 😄
